/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Company"][];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{ensName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ensName: components["schemas"]["EnsName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Company"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ipfs/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin sanitized file to IPFS */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        filename?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PinResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ipfs/pin-json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin canonical report JSON, return cid + reportHash */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportPayload"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cid: components["schemas"]["Cid"];
                            reportHash: components["schemas"]["Hex32"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proofs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit proof request (async). Returns 202 + requestId. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProofRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProofJob"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proofs/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll proof status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProofJob"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    company?: components["schemas"]["EnsName"];
                    category?: components["schemas"]["ReportCategory"];
                    since?: number;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Report"][];
                            nextCursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportHash: components["schemas"]["Hex32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Report"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportHash}/contextPack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apify Context Pack (X402-gated). 402 first; second call with PAYMENT-SIGNATURE returns 202. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportHash: components["schemas"]["Hex32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enrichment scheduled */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            contextPackCid: components["schemas"]["Cid"];
                        };
                    };
                };
                /** @description Payment required (x402) */
                402: {
                    headers: {
                        /** @description base64(JSON PaymentChallenge) */
                        "PAYMENT-REQUIRED"?: string;
                        /** @description X402 */
                        "X-APIFY-PAYMENT-PROTOCOL"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentChallenge"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pseudonyms/{pseudonymNode}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pseudonymNode: components["schemas"]["Hex32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pseudonymNode: components["schemas"]["Hex32"];
                            reportsCount: number;
                            verifiedCount: number;
                            debunkedCount: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Hex32: string;
        Address: string;
        EnsName: string;
        Cid: string;
        /** @enum {string} */
        ReportCategory: "Misconduct" | "SelectiveDisclosure" | "Misclassification" | "HollowPromise" | "InNameOnly" | "MisleadingPresentation";
        Company: {
            ensName: components["schemas"]["EnsName"];
            ensNode: components["schemas"]["Hex32"];
            admin: components["schemas"]["Address"];
            active: boolean;
            badgeTreeRoot: components["schemas"]["Hex32"];
            rootHistory?: components["schemas"]["Hex32"][];
            /** Format: int64 */
            registeredAt: number;
        };
        EvidenceItem: {
            cid: components["schemas"]["Cid"];
            filename: string;
            mime: string;
            sha256: components["schemas"]["Hex32"];
            sanitized?: {
                tool?: string;
                version?: string;
            };
        };
        ReportPayload: {
            /** @constant */
            version: 1;
            company: {
                ensName: components["schemas"]["EnsName"];
                ensNode: components["schemas"]["Hex32"];
            };
            category: components["schemas"]["ReportCategory"];
            title: string;
            summary: string;
            structuredFields: {
                [key: string]: unknown;
            };
            evidence: components["schemas"]["EvidenceItem"][];
            /** Format: date-time */
            submittedAt: string;
            pseudonym: components["schemas"]["EnsName"];
        };
        ProofRequest: {
            ensNode: components["schemas"]["Hex32"];
            reportHash: components["schemas"]["Hex32"];
            /** Format: int64 */
            periodId: number;
            badge: components["schemas"]["Hex32"];
            merklePath: components["schemas"]["Hex32"][];
            merkleIndices: number[];
        };
        ProofJob: {
            requestId: string;
            /** @enum {string} */
            status: "queued" | "fulfilled" | "failed" | "expired";
            /** Format: int64 */
            expiresAt: number;
            receipt?: components["schemas"]["ProofReceipt"];
            error?: string;
        };
        ProofReceipt: {
            seal: string;
            imageId: components["schemas"]["Hex32"];
            journal: {
                root: components["schemas"]["Hex32"];
                reportHash: components["schemas"]["Hex32"];
                nullifier: components["schemas"]["Hex32"];
                /** Format: int64 */
                periodId: number;
                ensNode: components["schemas"]["Hex32"];
            };
        };
        Report: {
            reportHash: components["schemas"]["Hex32"];
            ensNode: components["schemas"]["Hex32"];
            nullifier: components["schemas"]["Hex32"];
            rootUsed: components["schemas"]["Hex32"];
            cid: components["schemas"]["Cid"];
            category: components["schemas"]["ReportCategory"];
            /** Format: int64 */
            submittedAt: number;
            pseudonymNode: components["schemas"]["Hex32"];
            txHash: components["schemas"]["Hex32"];
            /** Format: int64 */
            blockNumber: number;
            payload?: components["schemas"]["ReportPayload"];
            contextPackCid?: string | null;
        };
        PinResult: {
            cid: components["schemas"]["Cid"];
            size: number;
        };
        PaymentRequirements: {
            /** @example exact */
            scheme: string;
            /** @example eip155:8453 */
            network: string;
            asset: components["schemas"]["Address"];
            /** @example 1000000 */
            amount: string;
            payTo: components["schemas"]["Address"];
            resource: string;
            maxTimeoutSeconds: number;
            extra?: {
                [key: string]: unknown;
            };
        };
        PaymentChallenge: {
            /** @constant */
            x402Version: 2;
            accepted: components["schemas"]["PaymentRequirements"][];
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
